//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mba_student_data
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> date_of_birth { get; set; }
        public string enrollment_no { get; set; }
        public string mobile_no { get; set; }
        public string email_id { get; set; }
        public string blood_group { get; set; }
        public string nationality { get; set; }
        public string religion { get; set; }
        public string father_name { get; set; }
        public string father_mobile_no { get; set; }
        public string father_email_id { get; set; }
        public string mother_name { get; set; }
        public string mother_mobile_no { get; set; }
        public string mother_email_id { get; set; }
        public string address_for_communication { get; set; }
        public string local_guardian_name { get; set; }
        public string local_guardian_mobile { get; set; }
        public string local_guardian_email_id { get; set; }
        public string local_guardian_address { get; set; }
        public string parents_income_category { get; set; }
        public string work_experience { get; set; }
    }
}
